Fix build for LDFLAGS="-Wl,--as-needed".
Commit 4f2646506d048613e287f3f6990c6633b1812e17 breaks b/c
thirdparty/lxt_write.c:1502 has undefined reference to `BZ2_bzdopen'.