Fix following splint warnings.
src/util.c: (in function fmt_loc)
src/util.c:313:50: Format argument 2 to fprintf (%d) expects int gets
uint16_t:
                      loc->first_line
  To allow arbitrary integral types to match any integral type, use
  +matchanyintegral.
   src/util.c:313:33: Corresponding format code
src/util.c:335:16: Operands of < have incompatible types (int, arbitrary
                      unsigned integral type): j < loc->first_column + 4
src/util.c:338:16: Operands of < have incompatible types (int, arbitrary
    unsigned integral type): j < last_col - loc->first_column + 1